name: Build Release

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - "package.json"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.run_number != 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}
          submodules: true

      - name: Get packageName
        id: packageName
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
            path: "package.json"
            prop_path: "name"
          
      - name: Set PackageName Variable
        run: |
          echo "packageName=${{steps.packageName.outputs.prop}}" >> $GITHUB_ENV
          
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
            path: "package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
        
      - name: Move files and List targets
        run: |
          shopt -s extglob
          mkdir -p "Packages/${{env.packageName}}"
          mv !("Packages") "Packages/${{env.packageName}}/"

      - name: Create Zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          directory: "./Packages/${{env.packageName}}"
          filename: "../../${{env.zipFile}}"
          exclusions: '*.git*'

      - name: Make Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          target_commitish: ${{ github.head_ref || github.ref_name }} 
          prerelease: ${{ contains(steps.version.outputs.prop, '-') }}
          files: |
            ${{env.zipFile}}
            Packages/${{env.packageName}}/package.json
